---
title: 十一、异常
---
# 十一、异常
## 1、异常分类
异常对象都是派生于Throwable类的实例，所有的异常都是由Throwable继承而来，在下一层分解为两个分支：Error和Exception    

Error类描述了Java运行时系统的内部错误和资源耗尽错误。  
Exception层次结构分解为两个分支，一个分支派生于RuntimeException，另一个分支包含其他异常。  
  
由程序错误导致的异常属于RuntimeException,而程序本身没有问题，但由于像I/O错误这类问题导致的异常属于其他异常。  
数组越界异常：ArrayIndexOutOfBoundsException  
变量为空异常：NullPointerException  
## 2、基本语法
  
	try{
		语句组
	}catch(Exception e){
		语句	
	}  
1）抛出异常：  
  
	throws 异常；//声明异常
	throw 异常对象；//抛出异常


	public static void readFile() throws IOException{//readFile方法有可能存在IO异常，此处声明有可能抛出IO异常
		FileInputStream in = new FileInputStream("myfile.txt");
		int b ;
		b = in.read();
		while(b != -1){
			System.out.print((char)b);
			b = in.read()
		}
		in.close();
	}
--------------------
	String readData(Scanner in) throws EOFException{
		...
		while(...){
			if(!in.hasNext()){
				if(n < len)
					throw new EOFException();
			}
			...
		}
		return s;
	}
2）捕获异常：  
  
	try{
		语句组;
	}catch(异常类名  异常形式参数名){
		异常处理语句组;
	}catch(异常类名  异常形式参数名){
		异常处理语句组  ;
	}finally{
		异常处理语句组；
	}
-------------------
	public void read(String filename){//读取文本，捕获异常
		try{
			InputStream in = new FileInputStream(filename);
			int b;
			while(b = in.read() != -1){
				process input
			}
		}
		catch(IOException exception){
			exception.printStackTrace();
		}
	}
catch语句可以有0到多个，可以没有finally语句。    
  
在main()函数中调用readFile()  
  
	import java.io.*;
	public class ExceptionTest{
		public static void main(String[] args){
			try{
				System.out.println("--------before-------");
				readFile();
				System.out.println("---------after---------");
			}catch(IOException e){
				System.out.println(e);
			}
		}
	}
3)再次抛出异常  
再次抛出异常的基本方法：  
  
	try{
		access the database
	}  
	catch(SQLException e){
		throw new ServletException("database error:" + e.getMessage());
		//ServletException用带有异常信息文本的构造器构造
	}
更好的方法如下，将原始异常设置为新异常的“原因”：  
  
	try{
		access database
	}
	catch(SQLException e){
		Throwable se = new ServletException("database error");
		se.initCause(e);
		throw se;
	}
当捕获异常后，可以重新得到原始异常：  
  
	Throwable e = se.getCause();
记录一个异常，在将它重新抛出，不做任何改变：  
  
	try{
		access database
	}
	catch(Exception e){
		logger.log(level , message , e);
		throw e;
	}
4)  带资源的try语句：  
  
	//try块退出时，会自动调用res.close()
	try(Resource res = ...){
		work with res
	}  
-----------------------------
	//这个块正常退出时，或者存在一个异常时，就好调用in.close()方法
	try(Scanner in = new Scanner(new FileInputStream("/usrs/...."))){
		while(in.hasNext())
			System.out.println(in.next());
	}

5）Exception类  
构造方法：  
  
	public Exception();  
	public Exception(String message);
	public Exception(String message,Throwable cause);
方法：  
  
	getMessage();
	getCause();
	printStackTrace();
## 3、自定义异常
自定义异常类就是一个派生于Exception或者是Exception子类的类。  
例如定义一个派生于IOException的类：  
  
	class FileFormatException extends IOException{//定义的类包含2个构造器
		public FileFormatException(){};//默认的构造器
		public FileFormatException(String gripe){//带有详细描述信息的构造器
			super(gripe);
		}
	}
-----------------
	//抛出自定义的异常类型
	String readData(BufferedReader in) throws FileFormatException{
		...
		while(...){
			if(ch == -1)//EOF encountered{
				if(n < len)
					throw new FileFormatException();
			}
			...
		}
		return s;
	}
## 4、断言
语法：  
  
	assert 条件;
	//或者
	assert 条件 ： 表达式;
-----------------
	public class Assertion{
		public static void main(String[] args){
			assert hypoenuse(3,4) == 5: "算法不正确"；
		}
		public static double hypoenuse(double x , double y){
			return Math.sqrt(x*x + y*y +1);
		}
	}

## 5、日志
1)、日志系统管理的默认日志记录器：Logger.global，并可以调用info方法记录日志信息。  
  
	Logger.getGlobal().info("File - > open menu item selected");
	//记录类容如下
	May 30,2018,15:02:20 PM LoggingImageViewer fileOpen
	INFO: File - > open menu item selected
2)、日志记录器级别  
SEVERE  

WARNING  

INFO  

CONFIG  

FINE  

FINER  

FINEST  

默认情况下只记录前三个级别，可以自己设置级别：  
  
	logger.setLevel( Level.FINE);//可以记录FINE和更高级别的记录
	Level.ALL     //开启所有级别记录
	Level.OFF     //关闭所有级别记录
对所有级别有下面几种记录方法：  
  
	logger.warning(message);
	logger.fine(message);
还可以使用log方法指定级别：  
  
	logger.log(Level.FINE , message);